version: "3.7"

services:
    db:
        image: mysql:8.0
        container_name: "${PROJECT_NAME}_db"
        restart: unless-stopped
        ports:
            - "${DATABASE_PORT}:3306"
        volumes:
            - './db_volume/db/data:/var/lib/mysql'
            - './db_volume/db/my.cnf:/etc/mysql/conf.d/my.cnf'
            - './db_volume/db/sql:/docker-entrypoint-initdb.d'
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: movies
            MYSQL_USER: app
            MYSQL_PASSWORD: app
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - app-network
volumes:
    db_volume:
        name: ${PROJECT_NAME}_db_volume

networks:
    app-network:
        driver: bridge
